[metadata]
name = "rhq"
description = "Browse the local repositoriy list"
requirements = ["rhq"]

[source]
command = "rhq list"

[preview]
command = "bat -n --color=always '{}'/README.md || true"
env = { BAT_THEME = "ansi" }
